### ISSUE TITLE
issue01 - Missing AccountId type validation

### ISSUE THREAD

**Issue by jw99l** [Vortex-Gaming-DAO/SmartContract#1]
In TypeScript, argument types are not automatically validated. This can result in funds being sent to invalid AccountIds or values being stored in the AccountId that use too much storage.

Affected Projects: Accessory, AvatarSBT, Composition, and Exchange with regards to AccountId.

Recommendation:
Ensure that AccountId is properly validated before use. 
- using the validateAccountId function from near-sdk-js
- by implementing custom validation logic based on the guidelines provided in [Account ID Rules](https://nomicon.io/DataStructures/Account#account-id-rules).

Example

```ts
import { validateAccountId } from "near-sdk-js";
...
    @call({ payableFunction: true })
    nft_transfer({ receiver_id, token_id, approval_id, memo }: {
        receiver_id: AccountId,
        token_id: TokenId,
        approval_id?: bigint,
        memo?: string
    }): void {
        assert(validateAccountId(receiver_id), "Receiver account ID is invalid");
...
```

**Comment by kalos-security** [comment]
https://github.com/Vortex-Gaming-DAO/SmartContract/commit/39b735c8f158164d789dfe180bb25bbf19756f25

**Comment by kalos-security** [comment]
Composition - update_nft
nft_token_id 도 validateAccountId 검증 필요합니다.

이외에는 잘 구현해주신것을 확인했습니다.

---
https://github.com/Vortex-Gaming-DAO/SmartContract/commit/7e31b87d42bd0500cd5d5210817ea97c861c277a
