### ISSUE TITLE
issue02 - Vulnerability in authorization verification using signerAccountId

### ISSUE THREAD

**Issue by jw99l** [Vortex-Gaming-DAO/SmartContract#2]
Using signerAccountId for authorization verification lead a vulnerability.

Context of Usage:
- Accessory - Minter verification (mt_mint)
- AvatarSBT - Minter verification (nft_mint, update_token_metadata)
- Composition - Oracle verification (update_nft)
- Exchange - Oracle verification (exchange_token)

In NEAR contracts, the signerAccountId function retrieves the account information of the entity that signed the transaction. If authorization checks are implemented using signerAccountId, transactions from accounts with elevated privileges need to be handled carefully. Specifically, if such transactions involve calling untrusted contracts or even trusted contracts that make external contract calls, the privileges of the account could be compromised.

Recommendation : Authorization checks should use predecessorAccountId instead of signerAccountId.

**Comment by kalos-security** [comment]
notion
