### ISSUE TITLE
issue03 - Missing defaultValue in Accessory Contract, causes inability to transfer to new accounts

### ISSUE THREAD

**Issue by jw99l** [Vortex-Gaming-DAO/SmartContract#3]
In the Accessory contract, there is an issue where transfers to new accounts fail due to the omission of a defaultValue option. When querying token_balances, the contract does not account for the possibility of the balance being undefined or null for new accounts. As a result, the mt_transfer function fails when attempting to transfer tokens to a new account.

https://github.com/Vortex-Gaming-DAO/SmartContract/blob/9b7f81062ef8b2b31751c1666ffa44819108748b/Accessory/contract/src/contractV2.ts#L270-L289

### Recommendation
By including (this.token_balances.get(..., { defaultValue: BigInt(0)), the contract assigns a default value of 0n (BigInt zero) if the balance for the receiver_id does not exist, thereby preventing the failure when transferring tokens to new accounts.

**Comment by kalos-security** [comment]
https://github.com/Vortex-Gaming-DAO/SmartContract/commit/566113db2ca990d82744cdfc0653c61de9c12ccb
